[package]
authors = ["Mac Lee <mal004@ucsd.edu>"]
name = "pv"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cache-size = "0.6"
clap = { version = "4.2", features = ["derive"]}
err-derive = "0.3"
derive_more = "0.99"
itertools = "0.10"
npyz = { version = "0.8", features = ["derive"]}
rayon = "1.7"
serde = { version = "1.0", features = ["serde_derive"] }
toml = "0.7"

[profile.release]
lto = true
